name: mark_space_app
description: Mark uploading web and native app


publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+3
  flutter_screenutil: ^3.2.0
  google_fonts: ^1.1.1
  page_transition:
  font_awesome_flutter: ^8.10.1
  flutter_launcher_icons: ^0.8.1
  url_launcher: ^5.7.10
  dio: ^3.0.10
  carousel_slider: ^2.3.1
  curved_navigation_bar: ^0.3.7
  loader_overlay: ^1.1.1
  flutter_spinkit: ^4.1.2
  flutter_speed_dial: ^1.2.5
  searchable_dropdown: ^1.1.3
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
