# Generated by Django 3.1.2 on 2021-01-26 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('assessments', models.ManyToManyField(blank=True, related_name='unit', to='mark_space_api.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='SubGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_grade_name', models.TextField()),
                ('sub_grade_mark', models.TextField()),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='mark_space_api.mark')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.student'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('period', models.TextField()),
                ('icon', models.URLField()),
                ('students', models.ManyToManyField(blank=True, related_name='class_student', to='mark_space_api.Student')),
                ('teachers', models.ManyToManyField(blank=True, related_name='class_teacher', to='mark_space_api.Teacher')),
                ('units', models.ManyToManyField(blank=True, related_name='class_unit', to='mark_space_api.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='marks',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='mark_space_api.Mark'),
        ),
    ]
