# Generated by Django 3.1.2 on 2020-12-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('period', models.TextField()),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('grade', models.FloatField()),
                ('subs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('marks', models.ManyToManyField(to='mark_space_api.Mark')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('teacher_classes', models.ManyToManyField(blank=True, to='mark_space_api.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('student_classes', models.ManyToManyField(blank=True, to='mark_space_api.Class')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Unit'),
        ),
    ]
