# Generated by Django 3.1.2 on 2020-12-25 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.TextField()),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('period', models.TextField()),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('assessments', models.ManyToManyField(blank=True, to='mark_space_api.Assessment')),
                ('the_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('teacher_classes', models.ManyToManyField(blank=True, to='mark_space_api.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('student_classes', models.ManyToManyField(blank=True, to='mark_space_api.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('subs', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Unit'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='marks',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.mark'),
        ),
    ]
