# Generated by Django 3.1.2 on 2020-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='the_class',
            field=models.ManyToManyField(related_name='classes', to='mark_space_api.Class'),
        ),
    ]
