# Generated by Django 3.1.2 on 2020-12-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='units',
        ),
        migrations.AddField(
            model_name='unit',
            name='the_class',
            field=models.OneToOneField(default='Functions', on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.class'),
            preserve_default=False,
        ),
    ]
