# Generated by Django 3.1.2 on 2020-12-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
    ]
