# Generated by Django 3.1.2 on 2020-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='marks',
        ),
        migrations.AddField(
            model_name='assessment',
            name='marks',
            field=models.ManyToManyField(blank=True, null=True, to='mark_space_api.Mark'),
        ),
    ]
