# Generated by Django 3.1.2 on 2021-01-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='grade',
            field=models.TextField(),
        ),
    ]
