# Generated by Django 3.1.2 on 2021-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgrade',
            name='grade',
        ),
        migrations.AddField(
            model_name='mark',
            name='subs',
            field=models.ManyToManyField(related_name='the_mark', to='mark_space_api.SubGrade'),
        ),
        migrations.AlterField(
            model_name='subgrade',
            name='mark',
            field=models.TextField(),
        ),
    ]
