# Generated by Django 3.1.2 on 2021-01-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0002_auto_20210111_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='subs',
            field=models.TextField(),
        ),
    ]
