# Generated by Django 3.1.2 on 2020-12-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0002_auto_20201224_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Unit'),
        ),
    ]
