# Generated by Django 3.1.2 on 2021-01-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0002_auto_20210105_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Unit'),
        ),
    ]
