# Generated by Django 3.1.2 on 2020-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0002_auto_20201227_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='weight',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='marks',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Mark'),
        ),
    ]
