# Generated by Django 3.1.2 on 2020-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0002_auto_20201217_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='the_class',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='the_class', to='mark_space_api.Class'),
        ),
    ]
