# Generated by Django 3.1.2 on 2020-12-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0002_remove_student_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='units',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Unit'),
        ),
    ]
