# Generated by Django 3.1.2 on 2021-01-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0003_auto_20210105_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='class',
            name='units',
        ),
    ]
