# Generated by Django 3.1.2 on 2020-12-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0003_auto_20201225_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='marks',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.mark'),
        ),
    ]
