# Generated by Django 3.1.2 on 2020-12-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0003_auto_20201217_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='student_classes',
            field=models.ManyToManyField(blank=True, related_name='student', to='mark_space_api.Class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_classes',
            field=models.ManyToManyField(blank=True, related_name='teacher', to='mark_space_api.Class'),
        ),
    ]
