# Generated by Django 3.1.2 on 2020-12-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0003_student_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='units',
        ),
    ]
