# Generated by Django 3.1.2 on 2020-12-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0004_auto_20201227_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='weight',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
