# Generated by Django 3.1.2 on 2020-12-18 00:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0004_auto_20201217_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_classes',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Class'),
        ),
    ]
