# Generated by Django 3.1.2 on 2020-12-25 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0004_auto_20201224_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.class'),
        ),
    ]
