# Generated by Django 3.1.2 on 2021-01-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0004_auto_20210105_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='the_class',
        ),
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Unit'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='mark_space_api.Class'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='assessments',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Assessment'),
        ),
    ]
