# Generated by Django 3.1.2 on 2020-12-18 02:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0005_auto_20201217_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
