# Generated by Django 3.1.2 on 2021-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0005_auto_20210105_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_classes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_classes',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='mark_space_api.Teacher'),
        ),
    ]
