# Generated by Django 3.1.2 on 2021-01-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0005_auto_20210113_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubGradeModel',
            new_name='SubGrade',
        ),
    ]
