# Generated by Django 3.1.2 on 2021-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0006_auto_20210105_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_student', to='mark_space_api.Student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='class_teacher', to='mark_space_api.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='class_unit', to='mark_space_api.Unit'),
        ),
    ]
