# Generated by Django 3.1.2 on 2021-01-30 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark_space_api.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='announcements',
            field=models.ManyToManyField(blank=True, related_name='class_announcement', to='mark_space_api.Announcement'),
        ),
    ]
