# Generated by Django 3.1.2 on 2021-02-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_space_api', '0002_auto_20210130_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
